// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contacts.proto
// Protobuf Java Version: 4.30.2

package org.liu.google.protobuf;

public final class Contacts {
  private Contacts() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Contacts.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code liu.PersonGender}
   */
  public enum PersonGender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>MAN = 1;</code>
     */
    MAN(1),
    /**
     * <code>FEMALE = 2;</code>
     */
    FEMALE(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        PersonGender.class.getName());
    }
    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>MAN = 1;</code>
     */
    public static final int MAN_VALUE = 1;
    /**
     * <code>FEMALE = 2;</code>
     */
    public static final int FEMALE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PersonGender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PersonGender forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return MAN;
        case 2: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PersonGender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PersonGender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PersonGender>() {
            public PersonGender findValueByNumber(int number) {
              return PersonGender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.liu.google.protobuf.Contacts.getDescriptor().getEnumTypes().get(0);
    }

    private static final PersonGender[] VALUES = values();

    public static PersonGender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PersonGender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:liu.PersonGender)
  }

  public interface PeopleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:liu.PeopleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 各个字段描述，格式为:   字段类型  字段名 = 字段唯一编号
     * 编号1-15用一个字节，编号16-2047用二个字节
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @return A list containing the phones.
     */
    java.util.List<java.lang.String>
        getPhonesList();
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @return The count of phones.
     */
    int getPhonesCount();
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @param index The index of the element to return.
     * @return The phones at the given index.
     */
    java.lang.String getPhones(int index);
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phones at the given index.
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);

    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    int getMpCount();
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    boolean containsMp(
        int key);
    /**
     * Use {@link #getMpMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getMp();
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getMpMap();
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    /* nullable */
java.lang.String getMpOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    java.lang.String getMpOrThrow(
        int key);

    /**
     * <code>.liu.PersonGender gender = 5;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <code>.liu.PersonGender gender = 5;</code>
     * @return The gender.
     */
    org.liu.google.protobuf.Contacts.PersonGender getGender();

    /**
     * <pre>
     * 此处idea标为红色，实际是没有问题，idea的问题
     * </pre>
     *
     * <code>.liu.ClientType client_type = 6;</code>
     * @return The enum numeric value on the wire for clientType.
     */
    int getClientTypeValue();
    /**
     * <pre>
     * 此处idea标为红色，实际是没有问题，idea的问题
     * </pre>
     *
     * <code>.liu.ClientType client_type = 6;</code>
     * @return The clientType.
     */
    org.liu.google.protobuf.BaseInfo.ClientType getClientType();
  }
  /**
   * <pre>
   * 结构化对象的描述
   * </pre>
   *
   * Protobuf type {@code liu.PeopleInfo}
   */
  public static final class PeopleInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:liu.PeopleInfo)
      PeopleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        PeopleInfo.class.getName());
    }
    // Use PeopleInfo.newBuilder() to construct.
    private PeopleInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PeopleInfo() {
      name_ = "";
      phones_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      gender_ = 0;
      clientType_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.liu.google.protobuf.Contacts.internal_static_liu_PeopleInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMp();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.liu.google.protobuf.Contacts.internal_static_liu_PeopleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.liu.google.protobuf.Contacts.PeopleInfo.class, org.liu.google.protobuf.Contacts.PeopleInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     * 各个字段描述，格式为:   字段类型  字段名 = 字段唯一编号
     * 编号1-15用一个字节，编号16-2047用二个字节
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList phones_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @return A list containing the phones.
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @return The count of phones.
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @param index The index of the element to return.
     * @return The phones at the given index.
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <pre>
     * 对应数组
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phones at the given index.
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    public static final int MP_FIELD_NUMBER = 4;
    private static final class MpDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  org.liu.google.protobuf.Contacts.internal_static_liu_PeopleInfo_MpEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> mp_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetMp() {
      if (mp_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MpDefaultEntryHolder.defaultEntry);
      }
      return mp_;
    }
    public int getMpCount() {
      return internalGetMp().getMap().size();
    }
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    @java.lang.Override
    public boolean containsMp(
        int key) {

      return internalGetMp().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMpMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getMp() {
      return getMpMap();
    }
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, java.lang.String> getMpMap() {
      return internalGetMp().getMap();
    }
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMpOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetMp().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, string&gt; mp = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getMpOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetMp().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int GENDER_FIELD_NUMBER = 5;
    private int gender_ = 0;
    /**
     * <code>.liu.PersonGender gender = 5;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.liu.PersonGender gender = 5;</code>
     * @return The gender.
     */
    @java.lang.Override public org.liu.google.protobuf.Contacts.PersonGender getGender() {
      org.liu.google.protobuf.Contacts.PersonGender result = org.liu.google.protobuf.Contacts.PersonGender.forNumber(gender_);
      return result == null ? org.liu.google.protobuf.Contacts.PersonGender.UNRECOGNIZED : result;
    }

    public static final int CLIENT_TYPE_FIELD_NUMBER = 6;
    private int clientType_ = 0;
    /**
     * <pre>
     * 此处idea标为红色，实际是没有问题，idea的问题
     * </pre>
     *
     * <code>.liu.ClientType client_type = 6;</code>
     * @return The enum numeric value on the wire for clientType.
     */
    @java.lang.Override public int getClientTypeValue() {
      return clientType_;
    }
    /**
     * <pre>
     * 此处idea标为红色，实际是没有问题，idea的问题
     * </pre>
     *
     * <code>.liu.ClientType client_type = 6;</code>
     * @return The clientType.
     */
    @java.lang.Override public org.liu.google.protobuf.BaseInfo.ClientType getClientType() {
      org.liu.google.protobuf.BaseInfo.ClientType result = org.liu.google.protobuf.BaseInfo.ClientType.forNumber(clientType_);
      return result == null ? org.liu.google.protobuf.BaseInfo.ClientType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, phones_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetMp(),
          MpDefaultEntryHolder.defaultEntry,
          4);
      if (gender_ != org.liu.google.protobuf.Contacts.PersonGender.UNKNOWN.getNumber()) {
        output.writeEnum(5, gender_);
      }
      if (clientType_ != org.liu.google.protobuf.BaseInfo.ClientType.ENUM_TYPE_NAME_UNSPECIFIED.getNumber()) {
        output.writeEnum(6, clientType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += computeStringSizeNoTag(phones_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetMp().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        mp__ = MpDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, mp__);
      }
      if (gender_ != org.liu.google.protobuf.Contacts.PersonGender.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, gender_);
      }
      if (clientType_ != org.liu.google.protobuf.BaseInfo.ClientType.ENUM_TYPE_NAME_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, clientType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.liu.google.protobuf.Contacts.PeopleInfo)) {
        return super.equals(obj);
      }
      org.liu.google.protobuf.Contacts.PeopleInfo other = (org.liu.google.protobuf.Contacts.PeopleInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPhonesList()
          .equals(other.getPhonesList())) return false;
      if (!internalGetMp().equals(
          other.internalGetMp())) return false;
      if (gender_ != other.gender_) return false;
      if (clientType_ != other.clientType_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      if (!internalGetMp().getMap().isEmpty()) {
        hash = (37 * hash) + MP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMp().hashCode();
      }
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + CLIENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + clientType_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.liu.google.protobuf.Contacts.PeopleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.liu.google.protobuf.Contacts.PeopleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.liu.google.protobuf.Contacts.PeopleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.liu.google.protobuf.Contacts.PeopleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 结构化对象的描述
     * </pre>
     *
     * Protobuf type {@code liu.PeopleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:liu.PeopleInfo)
        org.liu.google.protobuf.Contacts.PeopleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.liu.google.protobuf.Contacts.internal_static_liu_PeopleInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetMp();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableMp();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.liu.google.protobuf.Contacts.internal_static_liu_PeopleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.liu.google.protobuf.Contacts.PeopleInfo.class, org.liu.google.protobuf.Contacts.PeopleInfo.Builder.class);
      }

      // Construct using org.liu.google.protobuf.Contacts.PeopleInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        phones_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        internalGetMutableMp().clear();
        gender_ = 0;
        clientType_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.liu.google.protobuf.Contacts.internal_static_liu_PeopleInfo_descriptor;
      }

      @java.lang.Override
      public org.liu.google.protobuf.Contacts.PeopleInfo getDefaultInstanceForType() {
        return org.liu.google.protobuf.Contacts.PeopleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.liu.google.protobuf.Contacts.PeopleInfo build() {
        org.liu.google.protobuf.Contacts.PeopleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.liu.google.protobuf.Contacts.PeopleInfo buildPartial() {
        org.liu.google.protobuf.Contacts.PeopleInfo result = new org.liu.google.protobuf.Contacts.PeopleInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.liu.google.protobuf.Contacts.PeopleInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          phones_.makeImmutable();
          result.phones_ = phones_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.mp_ = internalGetMp();
          result.mp_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.clientType_ = clientType_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.liu.google.protobuf.Contacts.PeopleInfo) {
          return mergeFrom((org.liu.google.protobuf.Contacts.PeopleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.liu.google.protobuf.Contacts.PeopleInfo other) {
        if (other == org.liu.google.protobuf.Contacts.PeopleInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ |= 0x00000004;
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
        internalGetMutableMp().mergeFrom(
            other.internalGetMp());
        bitField0_ |= 0x00000008;
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (other.clientType_ != 0) {
          setClientTypeValue(other.getClientTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensurePhonesIsMutable();
                phones_.add(s);
                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
                mp__ = input.readMessage(
                    MpDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableMp().getMutableMap().put(
                    mp__.getKey(), mp__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                gender_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                clientType_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * 各个字段描述，格式为:   字段类型  字段名 = 字段唯一编号
       * 编号1-15用一个字节，编号16-2047用二个字节
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 各个字段描述，格式为:   字段类型  字段名 = 字段唯一编号
       * 编号1-15用一个字节，编号16-2047用二个字节
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 各个字段描述，格式为:   字段类型  字段名 = 字段唯一编号
       * 编号1-15用一个字节，编号16-2047用二个字节
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList phones_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensurePhonesIsMutable() {
        if (!phones_.isModifiable()) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @return A list containing the phones.
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        phones_.makeImmutable();
        return phones_;
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @return The count of phones.
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @param index The index of the element to return.
       * @return The phones at the given index.
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phones at the given index.
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @param index The index to set the value at.
       * @param value The phones to set.
       * @return This builder for chaining.
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @param value The phones to add.
       * @return This builder for chaining.
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePhonesIsMutable();
        phones_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @param values The phones to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhones() {
        phones_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应数组
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       * @param value The bytes of the phones to add.
       * @return This builder for chaining.
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensurePhonesIsMutable();
        phones_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> mp_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
          internalGetMp() {
        if (mp_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MpDefaultEntryHolder.defaultEntry);
        }
        return mp_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
          internalGetMutableMp() {
        if (mp_ == null) {
          mp_ = com.google.protobuf.MapField.newMapField(
              MpDefaultEntryHolder.defaultEntry);
        }
        if (!mp_.isMutable()) {
          mp_ = mp_.copy();
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return mp_;
      }
      public int getMpCount() {
        return internalGetMp().getMap().size();
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      @java.lang.Override
      public boolean containsMp(
          int key) {

        return internalGetMp().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMpMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getMp() {
        return getMpMap();
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, java.lang.String> getMpMap() {
        return internalGetMp().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getMpOrDefault(
          int key,
          /* nullable */
java.lang.String defaultValue) {

        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetMp().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      @java.lang.Override
      public java.lang.String getMpOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetMp().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearMp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableMp().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      public Builder removeMp(
          int key) {

        internalGetMutableMp().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
          getMutableMp() {
        bitField0_ |= 0x00000008;
        return internalGetMutableMp().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      public Builder putMp(
          int key,
          java.lang.String value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableMp().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; mp = 4;</code>
       */
      public Builder putAllMp(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableMp().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.liu.PersonGender gender = 5;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.liu.PersonGender gender = 5;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.liu.PersonGender gender = 5;</code>
       * @return The gender.
       */
      @java.lang.Override
      public org.liu.google.protobuf.Contacts.PersonGender getGender() {
        org.liu.google.protobuf.Contacts.PersonGender result = org.liu.google.protobuf.Contacts.PersonGender.forNumber(gender_);
        return result == null ? org.liu.google.protobuf.Contacts.PersonGender.UNRECOGNIZED : result;
      }
      /**
       * <code>.liu.PersonGender gender = 5;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(org.liu.google.protobuf.Contacts.PersonGender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.liu.PersonGender gender = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gender_ = 0;
        onChanged();
        return this;
      }

      private int clientType_ = 0;
      /**
       * <pre>
       * 此处idea标为红色，实际是没有问题，idea的问题
       * </pre>
       *
       * <code>.liu.ClientType client_type = 6;</code>
       * @return The enum numeric value on the wire for clientType.
       */
      @java.lang.Override public int getClientTypeValue() {
        return clientType_;
      }
      /**
       * <pre>
       * 此处idea标为红色，实际是没有问题，idea的问题
       * </pre>
       *
       * <code>.liu.ClientType client_type = 6;</code>
       * @param value The enum numeric value on the wire for clientType to set.
       * @return This builder for chaining.
       */
      public Builder setClientTypeValue(int value) {
        clientType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 此处idea标为红色，实际是没有问题，idea的问题
       * </pre>
       *
       * <code>.liu.ClientType client_type = 6;</code>
       * @return The clientType.
       */
      @java.lang.Override
      public org.liu.google.protobuf.BaseInfo.ClientType getClientType() {
        org.liu.google.protobuf.BaseInfo.ClientType result = org.liu.google.protobuf.BaseInfo.ClientType.forNumber(clientType_);
        return result == null ? org.liu.google.protobuf.BaseInfo.ClientType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 此处idea标为红色，实际是没有问题，idea的问题
       * </pre>
       *
       * <code>.liu.ClientType client_type = 6;</code>
       * @param value The clientType to set.
       * @return This builder for chaining.
       */
      public Builder setClientType(org.liu.google.protobuf.BaseInfo.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        clientType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 此处idea标为红色，实际是没有问题，idea的问题
       * </pre>
       *
       * <code>.liu.ClientType client_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clientType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:liu.PeopleInfo)
    }

    // @@protoc_insertion_point(class_scope:liu.PeopleInfo)
    private static final org.liu.google.protobuf.Contacts.PeopleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.liu.google.protobuf.Contacts.PeopleInfo();
    }

    public static org.liu.google.protobuf.Contacts.PeopleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PeopleInfo>
        PARSER = new com.google.protobuf.AbstractParser<PeopleInfo>() {
      @java.lang.Override
      public PeopleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PeopleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeopleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.liu.google.protobuf.Contacts.PeopleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liu_PeopleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_liu_PeopleInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liu_PeopleInfo_MpEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_liu_PeopleInfo_MpEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022\003liu\032\017base_info.proto\"\317" +
      "\001\n\nPeopleInfo\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      "\016\n\006phones\030\003 \003(\t\022#\n\002mp\030\004 \003(\0132\027.liu.People" +
      "Info.MpEntry\022!\n\006gender\030\005 \001(\0162\021.liu.Perso" +
      "nGender\022$\n\013client_type\030\006 \001(\0162\017.liu.Clien" +
      "tType\032)\n\007MpEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002" +
      " \001(\t:\0028\001*0\n\014PersonGender\022\013\n\007UNKNOWN\020\000\022\007\n" +
      "\003MAN\020\001\022\n\n\006FEMALE\020\002B\031\n\027org.liu.google.pro" +
      "tobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.liu.google.protobuf.BaseInfo.getDescriptor(),
        });
    internal_static_liu_PeopleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_liu_PeopleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_liu_PeopleInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Phones", "Mp", "Gender", "ClientType", });
    internal_static_liu_PeopleInfo_MpEntry_descriptor =
      internal_static_liu_PeopleInfo_descriptor.getNestedTypes().get(0);
    internal_static_liu_PeopleInfo_MpEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_liu_PeopleInfo_MpEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    org.liu.google.protobuf.BaseInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
