//created on: 2017-5-9
package com.sample.declares

declare Address
	id : String @key @maxLength(10)
	number : int
	streetName : String
	city : String
end

declare Animal
	name : String
	type : int
end

declare Person extends Animal
	@author(liu)
	@identity(123)
	id : String @key @maxLength(10)
	birthday : java.util.Date
	address : Address//上面定义的类型
end

rule "test declare"
    when
        //conditions
    then
        Address addr = new Address();
        addr.setId("liu123456789");
        addr.setNumber(10);
        addr.setStreetName("west street");
        addr.setCity("hangzhou");
        insert(addr);

end

